import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EM list App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen container mx-auto px-4 lg:px-6">
          <header className="border-b-2 py-5">Header</header>
          <div className="py-5">{children}</div>
        </div>
      </body>
    </html>
  );
}
